#
# Build test program
#

chine_test: ../chine.c ../unix/chine_sys_unix.c chine_test.c
	$(CC) -o $@ ../chine.c ../unix/chine_sys_unix.c chine_test.c

chine_test3: ../chine.c ../unix/chine_sys_unix.c chine_test3.c
	$(CC)  -o $@ ../chine.c ../unix/chine_sys_unix.c chine_test3.c
